#!/usr/bin/env perl

package Foo;
use Mojo::Base 'Mojolicious::Controller';

sub bar { shift->render_text("this is another controller (used by beer/list)"); }

package main;

use Mojolicious::Lite;
use lib './lib';

get '/beer/list' => { controller => "Foo", action => 'bar', nav_item => 'beverage' } => 'beer/list';

#plugin 'toto' =>
#   menu => [
#       beer    => { one  => [qw/view edit pictures notes/],
#                    many => [qw/list create search browse/] },
#       brewery => { one  => [qw/view edit directions beers info/],
#                    many => [qw/phonelist mailing_list/] },
#       pub     => { one  => [qw/view info comments hours/],
#                    many => [qw/search map/] },
#   ],
#;

plugin 'toto' =>
  nav => [
      'brewpub', # Refers to a sidenav entry below
      'beverage' # Refers to a sidenav entry below
  ],
  sidenav => {
    brewpub => [
        'brewery/phonelist', 'brewery/mailing_list',
        'pub/search',        'pub/map',
        'brewery', # Refers to a "tab" entry below
        'pub',     # Refers to a "tab" entry below
    ],
    beverage =>
      [ 'beer/list',
        'beer/create',
        'beer/search',
        'beer/browse',
        'beer'     # Refers to a "tab" entry below
       ],
  },
  tabs => {
    brewery => [ 'view', 'edit', 'directions', 'beers', 'info' ],
    pub     => [ 'view', 'info', 'comments', 'hours' ],
    beer    => [ 'view', 'edit', 'pictures', 'notes' ],
  };

app->start

